name: counter
description: 'Counter action'
author: mchmarny
branding:
  icon: arrow-up
  color: gray-dark
inputs:
  state:
    description: 'State file path'
    required: true
  key:
    description: 'State set key'
    required: true
  operation:
    description: 'Operation to perform'
    required: true
  value:
    description: 'Value for the action'
    required: false
    default: '0'
outputs:
  result:
    description: 'The result of the action'

runs:
  using: docker
  image: docker://ghcr.io/mchmarny/ghstore:latest
