name: calculator

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  calculate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DATA_FILE: data.db
    steps:

    - name: Checkout
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f  # v3.4.0

    - name: Calculate
      id: cal
      uses: mchmarny/ghstore@main
      with:
        data: ${{ env.DATA_FILE }}
        counter: calc
        action: add
        value: '1'
        
    - name: Save
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git add ${{ env.DATA_FILE }}
        git commit -am "save ${{ env.DATA_FILE }}"
        git push origin main