name: demo

on:
  workflow_dispatch:
    inputs:
      data_file:
        description: 'Path to data file (default: db/data.db)'
        required: false
        type: string
        default: db/data.db
      data_key:
        description: 'Data key (default: calculator)'
        required: false
        type: string
        default: calculator

permissions:
  contents: read

jobs:

  build:
    permissions:
      contents: read
      actions: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build.yaml

  demo:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3  # v3.5.0

    - name: Get
      id: get
      uses: mchmarny/ghstore@main
      with:
        state: ${{ inputs.data_file }}  # will be created if doesn't exist
        key: ${{ inputs.data_key }}
        operation: get

    - name: Print Get Output
      run: |-
        set -euo pipefail
        echo "Current value: ${{ steps.get.outputs.value }}"

    - name: Add
      uses: mchmarny/ghstore@main
      with:
        state: ${{ inputs.data_file }}
        key: ${{ inputs.data_key }}
        operation: add
        value: '10'

    - name: Sub
      id: sub
      uses: mchmarny/ghstore@main
      with:
        state: ${{ inputs.data_file }}
        key: ${{ inputs.data_key }}
        operation: sub
        value: '3'

    - name: Print Final Output
      run: |-
        set -euo pipefail
        echo "Current value: ${{ steps.sub.outputs.value }}"

    - name: Save
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git add ${{ env.DATA_FILE }}
        git commit -am "save ${{ env.DATA_FILE }}"
        git push origin main