name: demo

on:
  workflow_dispatch:
    inputs:
      data_file:
        description: 'Path to data file (default: db/data.db)'
        required: false
        type: string
        default: db/data.db
      data_key:
        description: 'Data key (default: calculator)'
        required: false
        type: string
        default: calculator

permissions:
  contents: read

jobs:

  demo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2

    - name: Get
      id: get
      uses: mchmarny/ghstore@main
      with:
        state: ${{ inputs.data_file }}  # will be created if doesn't exist
        key: ${{ inputs.data_key }}
        operation: get

    - name: Print Get Output
      run: |-
        set -euo pipefail
        echo "Current value: ${{ steps.get.outputs.value }}"

    - name: Add
      uses: mchmarny/ghstore@main
      with:
        state: ${{ inputs.data_file }}
        key: ${{ inputs.data_key }}
        operation: add
        value: '10'

    - name: Sub
      id: sub
      uses: mchmarny/ghstore@main
      with:
        state: ${{ inputs.data_file }}
        key: ${{ inputs.data_key }}
        operation: sub
        value: '3'

    - name: Print Final Output
      run: |-
        set -euo pipefail
        echo "Current value: ${{ steps.sub.outputs.value }}"

    - name: Save
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git add ${{ inputs.data_file }}
        git commit -am "save ${{ inputs.data_file }}"
        git push origin main
