name: demo

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  build:
    permissions:
      contents: read
      actions: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build.yaml

  demo:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DATA_FILE: db/calc.db
      DATE_KEY: calculator
    steps:

    - name: Checkout
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3  # v3.5.0

    - name: Get
      id: get
      uses: mchmarny/ghstore@main
      with:
        state: ${{ env.DATA_FILE }}  # will be created if doesn't exist
        key: ${{ env.DATE_KEY }}
        operation: get

    - name: Print Get Output
      run: |-
        set -euo pipefail
        echo "Current value: ${{ steps.get.outputs.value }}"

    - name: Add
      uses: mchmarny/ghstore@main
      with:
        state: ${{ env.DATA_FILE }}
        key: ${{ env.DATE_KEY }}
        operation: add
        value: '10'

    - name: Sub
      id: sub
      uses: mchmarny/ghstore@main
      with:
        state: ${{ env.DATA_FILE }}
        key: ${{ env.DATE_KEY }}
        operation: sub
        value: '3'

    - name: Print Final Output
      run: |-
        set -euo pipefail
        echo "Current value: ${{ steps.sub.outputs.value }}"

    - name: Save
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git add ${{ env.DATA_FILE }}
        git commit -am "save ${{ env.DATA_FILE }}"
        git push origin main