name: valid

on:
  workflow_call:
    inputs:
      file:
        description: 'File path'
        required: true
        type: string
      required:
        description: 'Whether or not it is required'
        type: boolean
        default: false
    outputs:
      output:
        value: ${{ jobs.valid.outputs.output }}
      processed_on:
        value: ${{ jobs.valid.outputs.processed_on }}

permissions:
  contents: read

jobs:
  valid:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      output: ${{ steps.validation.outputs.output }}
      processed_on: ${{ steps.validation.outputs.processed_on }}
    steps:

    - name: Checkout Code
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f  # v3.4.0

    - id: validation
      uses: mchmarny/template-action@main  # pinned to digest in real use
      with:
        file: ${{ inputs.file }}
        required: ${{ inputs.required }}