name: valid

on:
  workflow_call:
    inputs:
      file:
        description: 'File path'
        required: true
        type: string
      required:
        description: 'Whether or not it is required'
        type: boolean
        default: false
    outputs:
      output:
        result: ${{ jobs.valid.outputs.result }}

permissions:
  contents: read

jobs:
  valid:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      result: ${{ steps.validation.outputs.result }}
    steps:

    - name: Checkout Code
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f  # v3.4.0

    - id: validation
      uses: ./
      with:
        data: data.db
        counter: test
        action: add
        value: 1
